# Generated by Django 3.0.4 on 2020-04-10 00:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='date submitted')),
                ('content', models.TextField(help_text='sentence')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('sessionKey', models.CharField(max_length=200)),
                ('unionId', models.CharField(max_length=200)),
                ('avatarUrl', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('gender', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=200)),
                ('nickName', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='translate')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('numberOfLikes', models.IntegerField(default=0)),
                ('numberOfComments', models.IntegerField(default=0)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.User')),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.User'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='comment')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Translate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.User')),
            ],
        ),
    ]
