# Generated by Django 3.0.4 on 2020-04-07 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='date submitted')),
                ('content', models.TextField(help_text='sentence')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openId', models.CharField(max_length=200)),
                ('sessionKey', models.CharField(max_length=200)),
                ('unionId', models.CharField(max_length=200)),
                ('avatarUrl', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('nickName', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='translate')),
                ('numberOfLikes', models.IntegerField()),
                ('numberOfComments', models.IntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.User')),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.User'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='comment')),
                ('translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.Translate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.User')),
            ],
        ),
    ]
