# Generated by Django 3.0.4 on 2020-04-10 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0002_auto_20200410_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mps.User'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mps.User'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mps.Sentence'),
        ),
    ]
