# Generated by Django 3.0.4 on 2020-04-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0002_auto_20200407_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
