# Generated by Django 3.0.4 on 2020-04-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0003_auto_20200407_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
