# Generated by Django 3.0.4 on 2020-04-08 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0004_auto_20200407_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 4, 55, 52, 872448, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 8), help_text='date submitted'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='numberOfComments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='translate',
            name='numberOfLikes',
            field=models.IntegerField(default=0),
        ),
    ]
