# Generated by Django 3.0.4 on 2020-04-08 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0005_auto_20200408_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='date submitted'),
        ),
    ]
