# Generated by Django 3.0.4 on 2020-04-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0008_auto_20200408_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps.User'),
        ),
    ]
